import 'dotenv/config';
import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import { challenges, moments, config } from '../src/lib/db/schema';

const client = postgres(process.env.DATABASE_URL!);
const db = drizzle(client);

async function seed() {
  console.log('Seeding challenges...');
  await db.insert(challenges).values([
    {
      title: 'La cérémonie vue de votre place',
      description: 'Montrez-nous la cérémonie telle que vous la voyez depuis votre siège',
      points: 30,
      unlockAt: new Date('2026-05-23T14:30:00Z'), // 16h30 CEST
      sortOrder: 1,
      isActive: false,
    },
    {
      title: 'La première danse',
      description: 'Capturez la première danse des mariés depuis votre angle',
      points: 50,
      sortOrder: 2,
      isActive: true,
    },
    {
      title: "Selfie avec un(e) inconnu(e)",
      description: "Faites connaissance avec quelqu'un de l'autre famille et prenez un selfie ensemble",
      points: 30,
      sortOrder: 3,
      isActive: true,
    },
    {
      title: "Le dancefloor vu d'en haut",
      description: 'Trouvez un point de vue en hauteur pour photographier la piste de danse',
      points: 40,
      sortOrder: 4,
      isActive: true,
    },
    {
      title: 'Le moment le plus émouvant',
      description: 'Capturez LE moment qui vous a fait monter les larmes',
      points: 100,
      sortOrder: 5,
      isActive: true,
    },
    {
      title: 'Le détail déco le plus original',
      description: 'La déco est pleine de surprises... Trouvez la plus originale',
      points: 20,
      sortOrder: 6,
      isActive: true,
    },
    {
      title: 'Les enfants en action',
      description: 'Les enfants sont les vraies stars — immortalisez leurs bêtises',
      points: 30,
      sortOrder: 7,
      isActive: true,
    },
    {
      title: 'Le plat que vous avez préféré',
      description: 'Photographiez votre plat préféré du repas',
      points: 20,
      unlockAt: new Date('2026-05-23T17:00:00Z'), // 19h00 CEST
      sortOrder: 8,
      isActive: false,
    },
    {
      title: 'La piste à son apogée',
      description: 'Le moment où la piste de danse est la plus remplie',
      points: 50,
      unlockAt: new Date('2026-05-23T20:00:00Z'), // 22h00 CEST
      sortOrder: 9,
      isActive: false,
    },
    {
      title: 'Le dernier debout',
      description: 'Qui sera le dernier sur la piste ? Prouvez-le !',
      points: 100,
      unlockAt: new Date('2026-05-23T22:00:00Z'), // 00h00 CEST next day
      sortOrder: 10,
      isActive: false,
    },
  ]);

  console.log('Seeding moments...');
  await db.insert(moments).values([
    {
      label: 'Cérémonie',
      startTime: new Date('2026-05-23T14:30:00Z'),
      endTime: new Date('2026-05-23T15:15:00Z'),
      autoGenerated: false,
    },
    {
      label: 'Photos de groupe',
      startTime: new Date('2026-05-23T15:15:00Z'),
      endTime: new Date('2026-05-23T16:00:00Z'),
      autoGenerated: false,
    },
    {
      label: 'Cocktail',
      startTime: new Date('2026-05-23T16:00:00Z'),
      endTime: new Date('2026-05-23T17:30:00Z'),
      autoGenerated: false,
    },
    {
      label: 'Dîner',
      startTime: new Date('2026-05-23T17:30:00Z'),
      endTime: new Date('2026-05-23T19:30:00Z'),
      autoGenerated: false,
    },
    {
      label: 'Soirée dansante',
      startTime: new Date('2026-05-23T19:30:00Z'),
      endTime: new Date('2026-05-24T02:00:00Z'),
      autoGenerated: false,
    },
  ]);

  console.log('Seeding config...');
  await db.insert(config).values([
    {
      key: 'wedding',
      value: { groom: 'Malachie', bride: 'Jessica', date: '2026-05-23', city: 'Nantes' },
    },
    {
      key: 'theme',
      value: { primary: '#5B6B52', secondary: '#C4A882', accent: '#7B4F5C', bg: '#FAF8F5' },
    },
    {
      key: 'drive',
      value: { folder_id: '', all_moments_folder_id: '' },
    },
  ]);

  console.log('Seed complete!');
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});