import { NextResponse } from 'next/server';
import { getMomentsWithMedia } from '@/lib/db/queries/moments';
import { db } from '@/lib/db';
import { moments } from '@/lib/db/schema';
import { getAdminSession } from '@/lib/auth';

export async function GET() {
  const result = await getMomentsWithMedia();
  return NextResponse.json(result);
}

export async function POST(request: Request) {
  if (!(await getAdminSession())) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const body = await request.json();
  if (!body.startTime || !body.endTime) {
    return NextResponse.json(
      { error: 'startTime and endTime required' },
      { status: 400 }
    );
  }

  const [moment] = await db
    .insert(moments)
    .values({
      label: body.label || null,
      startTime: new Date(body.startTime),
      endTime: new Date(body.endTime),
      autoGenerated: false,
    })
    .returning();

  return NextResponse.json(moment, { status: 201 });
}
