import { NextResponse } from 'next/server';
import { getMomentsWithMedia } from '@/lib/db/queries/moments';
import { db } from '@/lib/db';
import { moments } from '@/lib/db/schema';
import { getAdminSession } from '@/lib/auth';
import { readJsonBody, asValidDate, asNonEmptyString } from '@/lib/validation';

export async function GET() {
  const result = await getMomentsWithMedia();
  return NextResponse.json(result);
}

export async function POST(request: Request) {
  if (!(await getAdminSession())) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const body = await readJsonBody(request);
  if (!body) {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 });
  }

  const startTime = asValidDate(body.startTime);
  const endTime = asValidDate(body.endTime);
  if (!startTime || !endTime) {
    return NextResponse.json(
      { error: 'valid startTime and endTime are required' },
      { status: 400 }
    );
  }
  if (startTime >= endTime) {
    return NextResponse.json(
      { error: 'startTime must be before endTime' },
      { status: 400 }
    );
  }

  const [moment] = await db
    .insert(moments)
    .values({
      label: asNonEmptyString(body.label),
      startTime,
      endTime,
      autoGenerated: false,
    })
    .returning();

  return NextResponse.json(moment, { status: 201 });
}
